# Created with EOSAIOS release tooling
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: EOSAIOS.EOSCLI
PackageVersion: 1.0.0-beta.29
InstallerType: zip
NestedInstallerType: portable
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: eos.exe
    PortableCommandAlias: eos
  InstallerUrl: https://github.com/eosaios/eos/releases/download/v1.0.0-beta.29/eos-cli_v1.0.0-beta.29_windows-amd64.zip
  InstallerSha256: 7BE4C38BE9511466E30433E9419CC6DCA6D58C695AD4F475089287C3462F3B0E
  ReleaseDate: 2026-09-23
ManifestType: installer
ManifestVersion: 1.10.0
