# Created with EOSAIOS release tooling
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.10.0.schema.json

PackageIdentifier: EOSAIOS.EOSCLI
PackageVersion: 1.0.0-beta.29
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.10.0
